/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-12-12 04:50:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enroll_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1732761397193L));
    _jspx_dependants.put("jar:file:/C:/bclass99/web-workspace2/RealSuperProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#hobby-wrap {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	align-items: baseline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox] {\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div style=\"width: 80%; margin: auto; padding: 50px;\">\r\n");
      out.write("		<form action=\"enroll.me\" name=\"signup\" id=\"signUpForm\" method=\"post\"\r\n");
      out.write("			style=\"margin-bottom: 0;\">\r\n");
      out.write("			<table\r\n");
      out.write("				style=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>아이디를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"idChk\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"text\" name=\"id\" id=\"user_id\"\r\n");
      out.write("						class=\"form-control tooltipstered\" maxlength=\"14\"\r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"숫자와 영어로 4-10자\"></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>비밀번호를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwChk\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"password\" size=\"17\" maxlength=\"20\"\r\n");
      out.write("						id=\"password\" name=\"pwd\" class=\"form-control tooltipstered\"\r\n");
      out.write("						maxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"영문과 특수문자를 포함한 최소 8자\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>비밀번호를 재확인해주세요.</strong>&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("								id=\"pwChk2\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"password\" size=\"17\" maxlength=\"20\"\r\n");
      out.write("						id=\"password_check\" name=\"pw_check\"\r\n");
      out.write("						class=\"form-control tooltipstered\" maxlength=\"20\"\r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"비밀번호가 일치해야합니다.\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>이름을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"nameChk\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"text\" name=\"name\" id=\"user_name\"\r\n");
      out.write("						class=\"form-control tooltipstered\" maxlength=\"6\"\r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"한글로 최대 6자\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>이메일을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("								id=\"emailChk\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"email\" name=\"email\" id=\"user_email\"\r\n");
      out.write("						class=\"form-control tooltipstered\" required=\"required\"\r\n");
      out.write("						aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"ex) kh@kh.com\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>취미를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"hobbyChk\"></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td id=\"hobby-wrap\"><input type=\"checkbox\" id=\"baseball\"\r\n");
      out.write("						value=\"야구\" name=\"interest\">&nbsp;<label for=\"baseball\">야구</label>\r\n");
      out.write("						<input type=\"checkbox\" id=\"device\" value=\"전자제품\" name=\"interest\">&nbsp;<label\r\n");
      out.write("						for=\"device\">전자제품</label> <input type=\"checkbox\" id=\"camping\"\r\n");
      out.write("						value=\"캠핑\" name=\"interest\">&nbsp;<label for=\"camping\">캠핑</label> <br>\r\n");
      out.write("\r\n");
      out.write("						<input type=\"checkbox\" id=\"farming\" value=\"농사\" name=\"interest\">&nbsp;<label\r\n");
      out.write("						for=\"farming\">농사</label> <input type=\"checkbox\" id=\"web\"\r\n");
      out.write("						value=\"web\" name=\"interest\">&nbsp;<label for=\"tea\">웹</label> <input\r\n");
      out.write("						type=\"checkbox\" id=\"java\" value=\"자바\" name=\"interest\">&nbsp;<label\r\n");
      out.write("						for=\"java\">자바</label></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<strong>회원가입하셔서 KH 수강생이 되어보세요~~!</strong>\r\n");
      out.write("						</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("						type=\"submit\" value=\"회원가입\" class=\"btn form-control tooltipstered\"\r\n");
      out.write("						id=\"signup-btn\"\r\n");
      out.write("						style=\"background-color: #52b1ff; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
